// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValiantXP.Infrastructure.Data;

#nullable disable

namespace ValiantXP.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706175049_AddPositionWinFields")]
    partial class AddPositionWinFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValiantXP.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RemoteIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CodeNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Codes", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.DynamicChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AnonParticipationAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("AntiFraudConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("NextChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionWinConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("DynamicChallenges");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.FailedAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SubmittedValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RemoteIp", "ChallengeId", "AttemptedAt")
                        .HasDatabaseName("IX_FailedAttempts_Ip_Challenge_Date");

                    b.HasIndex("UserId", "ChallengeId", "AttemptedAt")
                        .HasDatabaseName("IX_FailedAttempts_User_Challenge_Date");

                    b.ToTable("FailedAttempts", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GiftCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedeemUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("UserPrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("UserPrizeId");

                    b.HasIndex("ProviderId", "AssignedToUserId")
                        .HasDatabaseName("IX_GiftCards_Provider_Available");

                    b.HasIndex("ProviderId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_GiftCards_Provider_Code");

                    b.ToTable("GiftCards", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GiftCardProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InstructiveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_GiftCardProviders_Name");

                    b.ToTable("GiftCardProviders", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelHint")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConvertedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ConvertedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalHint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TtlMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedToUserId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_GuestSessions_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_GuestSessions_Token");

                    b.ToTable("GuestSessions", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Target", "IsUsed", "ExpiresAt");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowNoWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("DynamicChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("GiftCardProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsBaseReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPositionalReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxGlobalInWindow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxPerUserInWindow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PointMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PointsExpirationDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PrizeType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WindowHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DynamicChallengeId");

                    b.HasIndex("GiftCardProviderId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RallySubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DynamicChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsWinner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModerationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RallyType")
                        .HasColumnType("int");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubChallengeTag")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubmissionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextContent")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TicketDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("DynamicChallengeId", "Status");

                    b.HasIndex("DynamicChallengeId", "UserId");

                    b.ToTable("RallySubmissions", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RallySubmissionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RallySubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RemoteIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RallySubmissionId");

                    b.HasIndex("UserId", "RallySubmissionId")
                        .IsUnique();

                    b.HasIndex("UserId", "VotedAt");

                    b.ToTable("RallySubmissionVotes", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] != ''");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserChallengeProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DynamicChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReservedPrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DynamicChallengeId");

                    b.HasIndex("UserId", "DynamicChallengeId")
                        .IsUnique();

                    b.ToTable("UserChallengeProgresses");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailClaim")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserIdentities_UserId");

                    b.HasIndex("EmailClaim", "IsEmailVerified")
                        .HasDatabaseName("IX_UserIdentities_EmailClaim_Verified")
                        .HasFilter("[IsEmailVerified] = 1 AND [IsActive] = 1");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserIdentities_Provider_ExternalId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("UserIdentities", (string)null);
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserPointMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserPointMovements");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiftCardCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsRedeemed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PrizeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PrizeId", "AwardedAt");

                    b.HasIndex("UserId", "PrizeId");

                    b.ToTable("UserPrizes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Code", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.DynamicChallenge", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Challenges")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GiftCard", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("ValiantXP.Domain.Entities.GiftCardProvider", "Provider")
                        .WithMany("GiftCards")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.UserPrize", "UserPrize")
                        .WithMany()
                        .HasForeignKey("UserPrizeId");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Provider");

                    b.Navigation("UserPrize");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GiftCardProvider", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GuestSession", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.User", "ConvertedToUser")
                        .WithMany()
                        .HasForeignKey("ConvertedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConvertedToUser");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Prize", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.DynamicChallenge", "DynamicChallenge")
                        .WithMany("Prizes")
                        .HasForeignKey("DynamicChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.GiftCardProvider", "GiftCardProvider")
                        .WithMany("Prizes")
                        .HasForeignKey("GiftCardProviderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DynamicChallenge");

                    b.Navigation("GiftCardProvider");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RallySubmission", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.DynamicChallenge", "DynamicChallenge")
                        .WithMany()
                        .HasForeignKey("DynamicChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DynamicChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RallySubmissionVote", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.RallySubmission", "RallySubmission")
                        .WithMany("Votes")
                        .HasForeignKey("RallySubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RallySubmission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserChallengeProgress", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.DynamicChallenge", "DynamicChallenge")
                        .WithMany("UserProgresses")
                        .HasForeignKey("DynamicChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserIdentity", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserPointMovement", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.UserPrize", b =>
                {
                    b.HasOne("ValiantXP.Domain.Entities.Prize", "Prize")
                        .WithMany("UserPrizes")
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ValiantXP.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.DynamicChallenge", b =>
                {
                    b.Navigation("Prizes");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.GiftCardProvider", b =>
                {
                    b.Navigation("GiftCards");

                    b.Navigation("Prizes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.Prize", b =>
                {
                    b.Navigation("UserPrizes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.RallySubmission", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ValiantXP.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
